import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { callAIWithFallback, AI_ERRORS } from "../_shared/ai-provider.ts";

const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version" };

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { region, tone, campaignContext, narrativeContext, partyLevel, specificRequest } = await req.json();
    const systemPrompt = `Eres un diseñador de eventos sociales complejos para D&D 5e en Forgotten Realms. Creas encuentros sociales ricos, jugables y con múltiples capas de intriga. FORMATO DE RESPUESTA (JSON estricto): { "event_type": "tipo", "title": "nombre", "location": {"name": "lugar", "district": "zona", "city": "ciudad", "description": "ambientación"}, "occasion": "motivo", "atmosphere": "atmósfera", "key_attendees": [{"name": "nombre", "title": "cargo", "faction": "facción", "public_agenda": "agenda pública", "hidden_agenda": "agenda oculta", "secrets": ["secretos"], "personality_hook": "rasgo", "leverage": "palanca"}], "active_rumors": [{"rumor": "rumor", "truth_percentage": 50, "source_npc": "fuente", "purpose": "propósito"}], "social_conflicts": [{"conflict": "conflicto", "parties": ["partes"], "stakes": "en juego", "nonviolent_solutions": ["soluciones"]}], "roleplay_opportunities": [{"situation": "situación", "skills_useful": ["habilidades"], "potential_rewards": "recompensas", "risk": "riesgo"}], "potential_scandals": [{"scandal": "escándalo", "trigger": "detonante", "affected_parties": ["afectados"], "fallout": "consecuencias"}], "narrative_twists": [{"twist": "giro", "foreshadowing": "presagio", "trigger_condition": "condición", "impact": "impacto"}], "consequence_branches": [{"decision": "decisión", "outcome_a": "resultado A", "outcome_b": "resultado B", "long_term_impact": "impacto largo plazo"}], "timeline": [{"phase": "fase", "duration": "duración", "key_moments": "momentos", "opportunities": "oportunidades"}], "dm_notes": "notas DM", "summary": "resumen" }`;
    const userPrompt = `REGIÓN: ${region || "Forgotten Realms"}\nTONO: ${tone || "épico"}\nNIVEL: ${partyLevel || "5-10"}\n${specificRequest ? `PETICIÓN: ${specificRequest}` : ""}\nCONTEXTO:\n${JSON.stringify(campaignContext || {}, null, 2)}\nMEMORIA:\n${JSON.stringify(narrativeContext || {}, null, 2)}\nGenera un evento social complejo.`;
    const aiResult = await callAIWithFallback([{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }], { model: "gemini-2.5-pro", temperature: 0.85, response_mime_type: "application/json" });
    if (!aiResult) return new Response(JSON.stringify({ error: AI_ERRORS.ALL_UNAVAILABLE }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    const data = await aiResult.response.json(); const content = data.choices?.[0]?.message?.content;
    let socialEvent; try { socialEvent = JSON.parse(content); } catch { socialEvent = { raw: content, parse_error: true }; }
    return new Response(JSON.stringify({ socialEvent }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) { console.error("generate-social-event error:", error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
});