import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version" };

async function callAIWithFallback(messages: any[], options: { model?: string; temperature?: number; response_mime_type?: string } = {}) {
  const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY"); const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
  const geminiModel = options.model || "gemini-2.5-pro"; const body: any = { model: geminiModel, messages };
  if (options.temperature !== undefined) body.temperature = options.temperature; if (options.response_mime_type) body.response_mime_type = options.response_mime_type;
  if (GEMINI_API_KEY) { try { const resp = await fetch("https://generativelanguage.googleapis.com/v1beta/openai/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${GEMINI_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (resp.ok) return resp; if (resp.status === 429) console.log("Gemini rate limited..."); else console.error("Gemini error:", resp.status); } catch (e) { console.error("Gemini fetch error:", e); } }
  if (LOVABLE_API_KEY) { try { const lovBody = { ...body, model: `google/${geminiModel}` }; delete lovBody.response_mime_type; const resp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify(lovBody) }); if (resp.ok) return resp; if (resp.status === 429 || resp.status === 402) console.log("Lovable AI unavailable, trying ChatGPT..."); } catch (e) { console.error("Lovable AI error:", e); } }
  if (LOVABLE_API_KEY) { const m = geminiModel.includes("flash") ? "openai/gpt-5-mini" : "openai/gpt-5"; try { const chatBody = { ...body, model: m }; delete chatBody.response_mime_type; const resp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify(chatBody) }); if (resp.ok) return resp; } catch (e) { console.error("ChatGPT error:", e); } }
  return null;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { region, tone, campaignContext, narrativeContext, partyLevel, specificRequest } = await req.json();
    const systemPrompt = `Eres un diseñador de eventos sociales complejos para D&D 5e en Forgotten Realms. Creas encuentros sociales ricos, jugables y con múltiples capas de intriga. FORMATO DE RESPUESTA (JSON estricto): { "event_type": "tipo", "title": "nombre", "location": {"name": "lugar", "district": "zona", "city": "ciudad", "description": "ambientación"}, "occasion": "motivo", "atmosphere": "atmósfera", "key_attendees": [{"name": "nombre", "title": "cargo", "faction": "facción", "public_agenda": "agenda pública", "hidden_agenda": "agenda oculta", "secrets": ["secretos"], "personality_hook": "rasgo", "leverage": "palanca"}], "active_rumors": [{"rumor": "rumor", "truth_percentage": 50, "source_npc": "fuente", "purpose": "propósito"}], "social_conflicts": [{"conflict": "conflicto", "parties": ["partes"], "stakes": "en juego", "nonviolent_solutions": ["soluciones"]}], "roleplay_opportunities": [{"situation": "situación", "skills_useful": ["habilidades"], "potential_rewards": "recompensas", "risk": "riesgo"}], "potential_scandals": [{"scandal": "escándalo", "trigger": "detonante", "affected_parties": ["afectados"], "fallout": "consecuencias"}], "narrative_twists": [{"twist": "giro", "foreshadowing": "presagio", "trigger_condition": "condición", "impact": "impacto"}], "consequence_branches": [{"decision": "decisión", "outcome_a": "resultado A", "outcome_b": "resultado B", "long_term_impact": "impacto largo plazo"}], "timeline": [{"phase": "fase", "duration": "duración", "key_moments": "momentos", "opportunities": "oportunidades"}], "dm_notes": "notas DM", "summary": "resumen" }`;
    const userPrompt = `REGIÓN: ${region || "Forgotten Realms"}\nTONO: ${tone || "épico"}\nNIVEL: ${partyLevel || "5-10"}\n${specificRequest ? `PETICIÓN: ${specificRequest}` : ""}\nCONTEXTO:\n${JSON.stringify(campaignContext || {}, null, 2)}\nMEMORIA:\n${JSON.stringify(narrativeContext || {}, null, 2)}\nGenera un evento social complejo.`;
    const response = await callAIWithFallback([{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }], { model: "gemini-2.5-pro", temperature: 0.85, response_mime_type: "application/json" });
    if (!response) return new Response(JSON.stringify({ error: "Ambos servicios de IA están saturados. Espera unos segundos e inténtalo de nuevo." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    const data = await response.json(); const content = data.choices?.[0]?.message?.content;
    let socialEvent; try { socialEvent = JSON.parse(content); } catch { socialEvent = { raw: content, parse_error: true }; }
    return new Response(JSON.stringify({ socialEvent }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) { console.error("generate-social-event error:", error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
});