import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { callAIWithFallback } from "../_shared/ai-provider.ts";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version" };
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { region, tone, campaignContext, narrativeContext, partyLevel, mysteryType, specificRequest } = await req.json();
    const systemPrompt = `Eres un diseñador de arcos de investigación para D&D 5e en Forgotten Realms. Creas misterios complejos con la regla de los tres indicios. FORMATO (JSON estricto): {"title":"nombre","mystery_type":"tipo","hook":"gancho","crime_or_mystery":{"description":"qué pasó","victim":"víctima","when":"cuándo","where":"dónde","apparent_motive":"motivo aparente"},"hidden_truth":{"real_culprit":"culpable","real_motive":"motivo","method":"método","why_hidden":"por qué oculto"},"suspects":[{"name":"nombre","role":"cargo","motive":"motivo","means":"medios","opportunity":"oportunidad","alibi":"coartada","alibi_flaw":"fallo","guilty":false,"what_they_hide":"qué ocultan"}],"real_clues":[{"clue":"pista","location":"dónde","discovery_method":"cómo","what_it_reveals":"revela","connects_to":"conecta","difficulty":"medium"}],"false_leads":[{"clue":"pista falsa","why_misleading":"por qué","how_to_debunk":"cómo descartar","planted_by":"quién"}],"investigation_scenes":[{"scene":"escena","description":"desc","npcs_present":["PNJs"],"clues_available":["pistas"],"challenges":["obstáculos"],"skills_useful":["habilidades"],"possible_outcomes":["resultados"]}],"social_obstacles":[{"obstacle":"obstáculo","blocking_npc":"quién","motivation":"por qué","solutions":["soluciones"],"consequences_of_force":"consecuencias"}],"narrative_twists":[{"twist":"giro","trigger":"detonante","recontextualizes":"recontextualiza","emotional_impact":"impacto"}],"final_revelation":{"scene":"escena","dramatic_moment":"momento","proof":"prueba","culprit_reaction":"reacción","resolution_options":["opciones"]},"timeline":[{"phase":"fase","focus":"foco","key_scenes":["escenas"],"pacing_notes":"ritmo"}],"dm_notes":"notas","summary":"resumen"}`;
    const userPrompt = `REGIÓN: ${region || "Costa de la Espada"}\nTONO: ${tone || "épico"}\nNIVEL: ${partyLevel || "5-10"}\nTIPO: ${mysteryType || "cualquiera"}\n${specificRequest ? `PETICIÓN: ${specificRequest}` : ""}\nCONTEXTO:\n${JSON.stringify(campaignContext || {})}\nMEMORIA:\n${JSON.stringify(narrativeContext || {})}\nDiseña una investigación compleja.`;
    const aiResult = await callAIWithFallback([{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }], { model: "gemini-2.5-pro", temperature: 0.85, response_mime_type: "application/json" });
    if (!aiResult) return new Response(JSON.stringify({ error: "Ambos servicios de IA están saturados. Espera unos segundos." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    const data = await aiResult.response.json(); const content = data.choices?.[0]?.message?.content;
    let investigation; try { investigation = JSON.parse(content); } catch { investigation = { raw: content, parse_error: true }; }
    return new Response(JSON.stringify({ investigation }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) { console.error("generate-investigation error:", error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
});