import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version" };
async function callAIWithFallback(messages: any[], options: { model?: string; temperature?: number; response_mime_type?: string } = {}) {
  const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY"); const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
  const geminiModel = options.model || "gemini-2.5-pro"; const body: any = { model: geminiModel, messages };
  if (options.temperature !== undefined) body.temperature = options.temperature; if (options.response_mime_type) body.response_mime_type = options.response_mime_type;
  if (GEMINI_API_KEY) { const resp = await fetch("https://generativelanguage.googleapis.com/v1beta/openai/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${GEMINI_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (resp.ok) return resp; if (resp.status === 429) console.log("Gemini rate limited..."); else console.error("Gemini error:", resp.status); }
  if (LOVABLE_API_KEY) { const lovBody = { ...body, model: `google/${geminiModel}` }; delete lovBody.response_mime_type; const resp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify(lovBody) }); if (resp.ok) return resp; } return null;
}
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { recentEvents, partyDecisions, affectedNPCs, factions, activeConflicts, region, narrativeContext } = await req.json();
    const systemPrompt = `Eres un motor de consecuencias dinámicas para D&D 5e en Forgotten Realms. FORMATO (JSON): {"political_changes":[{"change":"desc","severity":"minor|moderate|major","affected_entities":["..."]}],"social_changes":[{"change":"desc","impact_area":"local|regional"}],"economic_changes":[{"change":"desc","direction":"positive|negative","sectors":["..."]}],"faction_reactions":[{"faction":"nombre","reaction":"desc","stance_shift":"friendly|neutral|hostile","actions_planned":"..."}],"emerging_conflicts":[{"conflict":"desc","parties_involved":["..."],"urgency":"low|medium|high|critical"}],"narrative_opportunities":[{"opportunity":"desc","type":"quest|alliance|discovery|betrayal","hooks":["..."]}],"future_threats":[{"threat":"desc","timeline":"immediate|short_term|long_term","danger_level":"low|medium|high|deadly"}],"rumors":[{"rumor":"desc","truth_percentage":50,"source":"taberna|mercado|templo|corte|submundo"}],"summary":"resumen"}`;
    const userPrompt = `EVENTOS:\n${JSON.stringify(recentEvents || [])}\nDECISIONES:\n${JSON.stringify(partyDecisions || [])}\nPNJs:\n${JSON.stringify(affectedNPCs || [])}\nFACCIONES:\n${JSON.stringify(factions || [])}\nCONFLICTOS:\n${JSON.stringify(activeConflicts || [])}\nREGIÓN: ${region || "No especificada"}\nMEMORIA:\n${JSON.stringify(narrativeContext || {})}\nGenera consecuencias dinámicas.`;
    const response = await callAIWithFallback([{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }], { model: "gemini-2.5-pro", temperature: 0.8, response_mime_type: "application/json" });
    if (!response) return new Response(JSON.stringify({ error: "Ambos servicios de IA están saturados. Espera unos segundos." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    const data = await response.json(); const content = data.choices?.[0]?.message?.content;
    let consequences; try { consequences = JSON.parse(content); } catch { consequences = { raw: content, parse_error: true }; }
    return new Response(JSON.stringify({ consequences }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) { console.error("generate-consequences error:", error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
});