import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { callAIWithFallback } from "../_shared/ai-provider.ts";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version" };
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { region, tone, campaignContext, narrativeContext, partyLevel, locationType, specificRequest } = await req.json();
    const systemPrompt = `Eres un diseñador de localizaciones vivas para D&D 5e en Forgotten Realms. FORMATO (JSON estricto): {"name":"nombre","type":"tipo","official_region":"región","brief_history":"historia","current_state":"estado","social_climate":{"general_mood":"ánimo","tensions":["tensiones"],"power_dynamics":"poder"},"economy":{"primary_industry":"industria","trade_goods":["bienes"],"economic_health":"stable","black_market":"mercado negro"},"factions_present":[{"faction":"nombre","influence":"medium","leader_local":"líder","agenda":"agenda","public_face":"cara pública","real_activity":"actividad real"}],"active_rumors":[{"rumor":"rumor","truth_percentage":50,"heard_at":"dónde","narrative_potential":"potencial"}],"local_conflicts":[{"conflict":"conflicto","parties":["partes"],"stakes":"en juego","current_status":"simmering"}],"key_locations":[{"name":"nombre","type":"tipo","description":"desc","owner":"dueño","notable_feature":"especial","hook":"gancho"}],"random_events":[{"event":"evento","trigger":"cuándo","probability":"common","consequences":"consecuencias"}],"resident_npcs":[{"name":"nombre","role":"rol","personality":"personalidad","secret":"secreto","useful_for":"utilidad","quest_hook":"misión"}],"hidden_secrets":[{"secret":"secreto","discovery_method":"método","narrative_impact":"impacto","danger_level":"medium"}],"atmosphere":{"sights":"vista","sounds":"sonidos","smells":"olores","feeling":"sensación"},"dm_notes":"notas","summary":"resumen"}`;
    const userPrompt = `REGIÓN: ${region || "Costa de la Espada"}\nTONO: ${tone || "épico"}\nNIVEL: ${partyLevel || "5-10"}\nTIPO: ${locationType || "cualquiera"}\n${specificRequest ? `PETICIÓN: ${specificRequest}` : ""}\nCONTEXTO:\n${JSON.stringify(campaignContext || {})}\nMEMORIA:\n${JSON.stringify(narrativeContext || {})}\nGenera una localización viva y jugable.`;
    const response = await callAIWithFallback([{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }], { model: "gemini-2.5-pro", temperature: 0.85, response_mime_type: "application/json" });
    if (!response) return new Response(JSON.stringify({ error: "Ambos servicios de IA están saturados. Espera unos segundos." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    const data = await response.json(); const content = data.choices?.[0]?.message?.content;
    let location; try { location = JSON.parse(content); } catch { location = { raw: content, parse_error: true }; }
    return new Response(JSON.stringify({ location }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) { console.error("generate-location error:", error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
});