import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { callAIWithFallback } from "../_shared/ai-provider.ts";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version" };
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { region, tone, campaignContext, narrativeContext, partyLevel, encounterTheme, specificRequest } = await req.json();
    const systemPrompt = `Eres un diseñador de encuentros híbridos para D&D 5e en Forgotten Realms. Combate, diplomacia e investigación coexisten. FORMATO (JSON): {"title":"nombre","encounter_type":"tipo","context":{"situation":"situación","location":"dónde","stakes":"en juego","time_pressure":"none|low|medium|high|critical","why_now":"por qué ahora"},"narrative_tension":{"opening_tension":"nivel","escalation_triggers":["triggers"],"deescalation_options":["opciones"],"point_of_no_return":"punto sin retorno"},"involved_parties":[{"name":"nombre","motivation":"motivación","disposition":"hostile|wary|neutral","negotiation_leverage":"palanca","combat_capability":"moderate","breaking_point":"punto de ruptura"}],"social_options":[{"approach":"enfoque","key_skills":["skills"],"key_arguments":["argumentos"],"npc_reactions":"reacciones","success_outcome":"éxito","partial_success":"parcial","failure_consequence":"fallo"}],"combat_scenario":{"enemies":[{"name":"nombre","cr":"CR","tactics":"táctica","morale_break":"moral"}],"terrain_features":["terreno"],"environmental_hazards":["peligros"],"victory_conditions":["condiciones"]},"stealth_option":{"approach":"enfoque","challenges":["retos"],"detection_consequences":"detección","success_outcome":"éxito"},"tipping_points":[{"trigger":"trigger","shifts_from":"social","shifts_to":"combat","can_be_reversed":true,"how_to_reverse":"cómo"}],"consequences_by_approach":{"full_combat":{"immediate":"inmediato","reputation_impact":"reputación","campaign_impact":"campaña"},"full_diplomacy":{"immediate":"inmediato","reputation_impact":"reputación","campaign_impact":"campaña"},"stealth_resolution":{"immediate":"inmediato","reputation_impact":"reputación","campaign_impact":"campaña"},"mixed_approach":{"immediate":"inmediato","reputation_impact":"reputación","campaign_impact":"campaña"}},"conflict_evolution":{"if_unresolved":"sin resolver","escalation_timeline":"timeline","future_repercussions":["consecuencias"]},"dm_notes":"notas","summary":"resumen"}`;
    const userPrompt = `REGIÓN: ${region || "Costa de la Espada"}\nTONO: ${tone || "épico"}\nNIVEL: ${partyLevel || "5-10"}\nTEMA: ${encounterTheme || "cualquiera"}\n${specificRequest ? `PETICIÓN: ${specificRequest}` : ""}\nCONTEXTO:\n${JSON.stringify(campaignContext || {})}\nMEMORIA:\n${JSON.stringify(narrativeContext || {})}\nDiseña un encuentro híbrido.`;
    const response = await callAIWithFallback([{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }], { model: "gemini-2.5-pro", temperature: 0.85, response_mime_type: "application/json" });
    if (!response) return new Response(JSON.stringify({ error: "Ambos servicios de IA están saturados. Espera unos segundos." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    const data = await response.json(); const content = data.choices?.[0]?.message?.content;
    let encounter; try { encounter = JSON.parse(content); } catch { encounter = { raw: content, parse_error: true }; }
    return new Response(JSON.stringify({ encounter }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) { console.error("generate-hybrid-encounter error:", error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
});