import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version" };
async function callAIWithFallback(messages: any[], options: { model?: string; temperature?: number; response_mime_type?: string } = {}) {
  const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY"); const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
  const geminiModel = options.model || "gemini-2.5-pro"; const body: any = { model: geminiModel, messages };
  if (options.temperature !== undefined) body.temperature = options.temperature; if (options.response_mime_type) body.response_mime_type = options.response_mime_type;
  if (GEMINI_API_KEY) { const resp = await fetch("https://generativelanguage.googleapis.com/v1beta/openai/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${GEMINI_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (resp.ok) return resp; if (resp.status === 429) console.log("Gemini rate limited..."); else console.error("Gemini error:", resp.status); }
  if (LOVABLE_API_KEY) { const lovBody = { ...body, model: `google/${geminiModel}` }; delete lovBody.response_mime_type; const resp = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify(lovBody) }); if (resp.ok) return resp; } return null;
}
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { region, tone, campaignContext, narrativeContext, partyLevel, dilemmaTheme, specificRequest } = await req.json();
    const systemPrompt = `Eres un diseñador de dilemas morales complejos para D&D 5e en Forgotten Realms. Ninguna opción es claramente correcta. FORMATO (JSON): {"title":"nombre","theme":"tema","initial_situation":{"description":"desc","urgency":"low|medium|high|critical","context":"contexto"},"involved_parties":[{"name":"nombre","role":"papel","motivation":"motivación","moral_standing":"posición moral","emotional_state":"estado","what_they_hide":"ocultan"}],"conflicting_interests":[{"interest":"interés","who_benefits":"beneficiario","who_suffers":"perjudicado","moral_weight":"peso"}],"incomplete_information":[{"what_pjs_know":"saben","what_pjs_dont_know":"no saben","how_to_discover":"descubrir","discovery_changes_everything":"cambio"}],"possible_decisions":[{"decision":"opción","immediate_appeal":"atractivo","hidden_cost":"coste","alignment_tendency":"alineamiento"}],"short_term_consequences":[{"decision":"si X","immediate_result":"resultado","who_reacts":"reacción","emotional_fallout":"impacto"}],"long_term_consequences":[{"decision":"si X","weeks_later":"semanas","months_later":"meses","permanent_change":"cambio permanente"}],"political_social_impact":[{"decision":"decisión","political_shift":"político","social_shift":"social","faction_reactions":[{"faction":"facción","reaction":"reacción"}]}],"npc_emotional_impact":[{"npc":"nombre","if_decision_a":"reacción A","if_decision_b":"reacción B","relationship_change":"cambio relación"}],"dm_notes":"notas","summary":"resumen"}`;
    const userPrompt = `REGIÓN: ${region || "FR"}\nTONO: ${tone || "épico"}\nNIVEL: ${partyLevel || "5-10"}\nTEMA: ${dilemmaTheme || "cualquiera"}\n${specificRequest ? `PETICIÓN: ${specificRequest}` : ""}\nCONTEXTO:\n${JSON.stringify(campaignContext || {})}\nMEMORIA:\n${JSON.stringify(narrativeContext || {})}\nGenera un dilema moral complejo.`;
    const response = await callAIWithFallback([{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }], { model: "gemini-2.5-pro", temperature: 0.85, response_mime_type: "application/json" });
    if (!response) return new Response(JSON.stringify({ error: "Ambos servicios de IA están saturados. Espera unos segundos." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    const data = await response.json(); const content = data.choices?.[0]?.message?.content;
    let dilemma; try { dilemma = JSON.parse(content); } catch { dilemma = { raw: content, parse_error: true }; }
    return new Response(JSON.stringify({ dilemma }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) { console.error("generate-moral-dilemma error:", error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
});