import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { callAIWithFallback } from "../_shared/ai-provider.ts";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version" };
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const { region, factions, openConflicts, growingThreats, recentPartyActions, timePassed, campaignContext, narrativeContext } = await req.json();
    const systemPrompt = `Eres un simulador de estado del mundo para D&D 5e en Forgotten Realms. Simulas eventos offscreen coherentes. FORMATO (JSON): {"time_simulated":"período","world_summary":"resumen","offscreen_events":[{"event":"qué","when":"cuándo","caused_by":"causa","witnesses":["testigos"],"public_knowledge":true,"impact":"impacto"}],"political_changes":[{"change":"cambio","old_state":"antes","new_state":"ahora","key_actors":["actores"],"stability":"stable|fragile|volatile"}],"faction_movements":[{"faction":"nombre","action_taken":"acción","motivation":"por qué","new_position":"posición","relation_to_party":"relación PJs"}],"new_rumors":[{"rumor":"rumor","truth_percentage":50,"spread":"local|regional","source_origin":"origen","narrative_hook":"gancho"}],"narrative_opportunities":[{"opportunity":"desc","type":"quest|alliance|discovery","time_sensitive":true,"expires_in":"tiempo","reward_potential":"recompensa"}],"emerging_threats":[{"threat":"amenaza","source":"origen","current_severity":"moderate","trajectory":"growing","if_ignored":"si ignoran"}],"environmental_changes":[{"change":"cambio","cause":"causa","affected_area":"zona","gameplay_impact":"impacto"}],"npc_status_updates":[{"npc":"nombre","previous_status":"antes","current_status":"ahora","reason":"razón","party_relevance":"relevancia"}],"dm_briefing":"briefing DM"}`;
    const userPrompt = `REGIÓN: ${region || "Costa de la Espada"}\nTIEMPO: ${timePassed || "1-2 semanas"}\nFACCIONES:\n${JSON.stringify(factions || [])}\nCONFLICTOS:\n${JSON.stringify(openConflicts || [])}\nAMENAZAS:\n${JSON.stringify(growingThreats || [])}\nACCIONES GRUPO:\n${JSON.stringify(recentPartyActions || [])}\nCONTEXTO:\n${JSON.stringify(campaignContext || {})}\nMEMORIA:\n${JSON.stringify(narrativeContext || {})}\nSimula qué ha ocurrido.`;
    const aiResult = await callAIWithFallback([{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }], { model: "gemini-2.5-pro", temperature: 0.8, response_mime_type: "application/json" });
    if (!aiResult) return new Response(JSON.stringify({ error: "Ambos servicios de IA están saturados. Espera unos segundos." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    const data = await aiResult.response.json(); const content = data.choices?.[0]?.message?.content;
    let simulation; try { simulation = JSON.parse(content); } catch { simulation = { raw: content, parse_error: true }; }
    return new Response(JSON.stringify({ simulation }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) { console.error("simulate-world-state error:", error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
});